# Generated by Django 2.2.20 on 2022-02-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputData', models.TextField(blank=True, null=True)),
                ('outputData', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
