# Generated by Django 2.2.20 on 2022-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
