# Generated by Django 2.2.20 on 2022-02-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_summary_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
